### ISSUE TITLE
Password reset email 

### ISSUE THREAD

**Issue by bakhshiqbal** [bakhshiqbal/collegeknight#11]
Password reset email doesn't actually work

**Comment by sairajaved** [comment]
Fixed.

**Comment by bakhshiqbal** [comment]
@sairajaved I tested this and didn't work for me.

**Comment by sairajaved** [comment]
please check

**Comment by bakhshiqbal** [comment]
@sairajaved strangely enough this still does not work for me.
